# -*- coding: utf-8 -*-
"""week_1_pset

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1igGn4rqrweJvvZ19CicnuLzj6Uz_XMzi

# Week One Problem Set: First Steps with Python

In our first week together, we started our discussion of the Python programming language, which will be the programming language on which we'll focus our attention in this course. More specifically, we took our first steps with Python by exploring some of the building blocks of the language, including the methods we can use to read files into memory, transform the data read into memory, and print the results of those transformations.

To help you develop mastery of these and other fundamental methods we will discuss in the course, we will ask you to complete "problem sets", or technical challenges, that cover the material we discuss in our in-class workshops.

This notebook contains our first problem set. To complete the problem set, all you need to do is to complete the individual coding challenges below. As you work to complete these challenges, you should feel free to consult any resources. Just remember that the goal of these challenges is to help you practice programming. If you get stuck on a coding challenge, you can always email us to ask for guidance.

## Printing the Value Assigned to a Variable

See if you can print the value assigned to `mystery_variable` below:
"""

mystery_variable = 6*7

# type your code below

"""## Reading Files into Memory

One of the most important tasks for data mining is the act of reading data (e.g. text files) into memory. For this task, download a text file from [Project Gutenberg](https://www.gutenberg.org/) to your personal machine.

Next, click the folder icon in the left-hand navigation toolbar, then click the icon that looks like a document with an upward arrow and select your file:

<img src='https://github.com/YaleDHLab/lab-workshops/raw/master/first-steps-with-python/assets/colab-file-upload.gif'>

After your Project Gutenberg text file is uploaded to this Colab environment, use the technique we practiced in class to read your file into memory and print the file contents to the screen:


"""

# type your code below

"""## Working with String Data

We spent some time in week one examining some of the methods we can call on "strings" (text data) in Python. Let's practice some of those methods below.

First, let's determine the set of methods we can call on the string below:
"""

text = '''
“Take some more tea,” the March Hare said to Alice, very earnestly.
“I’ve had nothing yet,” Alice replied in an offended tone: “so I ca’n’t take more.”
“You mean you ca’n’t take less,” said the Hatter: “It’s very easy to take more than nothing.”
'''

dir(text)

"""Examine the list of methods above, and see if you can accomplish the following tasks:

#### Transform `text` to uppercase
"""



"""#### Transform `text` to lowercase"""



"""#### Split `text` into a list of sentences"""



"""## Using Modules

Finally, we learned how we can use "modules" (or code others have written) in our Python programs. For our final challenge, see if you can use the `Counter` from the `collections` module to count the number of times each word occurs in the file you downloaded from Project Gutenberg.
"""

# type your code below